-- MySQL Script generated by MySQL Workbench
-- Wed May 10 09:13:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema colocations
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema colocations
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `colocations` DEFAULT CHARACTER SET utf8 ;
USE `colocations` ;

-- -----------------------------------------------------
-- Table `colocations`.`goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colocations`.`goods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `picture` VARCHAR(120) NOT NULL,
  `kindOfGood` VARCHAR(45) NOT NULL,
  `location` VARCHAR(70) NOT NULL,
  `address` VARCHAR(70) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `numberOfPieces` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UniqueGoods` (`address` ASC, `title` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colocations`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colocations`.`members` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colocations`.`members_has_goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colocations`.`members_has_goods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `member_id` INT NOT NULL,
  `good_id` INT NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  INDEX `fk_members_has_goods_goods1_idx` (`good_id` ASC) VISIBLE,
  INDEX `fk_members_has_goods_members_idx` (`member_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_members_has_goods_members`
    FOREIGN KEY (`member_id`)
    REFERENCES `colocations`.`members` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_members_has_goods_goods1`
    FOREIGN KEY (`good_id`)
    REFERENCES `colocations`.`goods` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
